import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import path from "path";
import swaggerUi from "swagger-ui-express";
import { swaggerSpec } from "./lib/swagger.js";
import authRoutes from "./routes/auth.routes.js";
import oauthRoutes from "./routes/oauth.routes.js";
import passport from "./lib/passport.js";
import recipeRoutes from "./routes/recipe.routes.js";
import cookbookRoutes from "./routes/cookbook.routes.js";
import searchRoutes from "./routes/search.routes.js";
import exportImportRoutes from "./routes/exportImport.routes.js";
import userRoutes from "./routes/user.routes.js";
import invitationRoutes from "./routes/invitation.routes.js";
import publicRoutes from "./routes/public.routes.js";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use(passport.initialize());
app.use("/uploads", express.static(path.resolve("uploads")));
app.use("/docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use("/api/auth", authRoutes);
app.use("/api/auth", oauthRoutes);
app.use("/api/recipes", recipeRoutes);
app.use("/api/cookbooks", cookbookRoutes);
app.use("/api/search", searchRoutes);
app.use("/api", exportImportRoutes);
app.use("/api/users", userRoutes);
app.use("/api/invitations", invitationRoutes);
app.use("/api/public", publicRoutes);
app.get("/api/health", (req, res) => res.json({ status: "ok" }));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`SUPMEAL server running on port ${PORT}`));
